# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5edeb49d96a90b95bf9afbbcd0d6196e7ff33181f049e7beec6cef9f2e15f992427bf530b3f5dd941ccac7a6f1a571a448a35f72d3cbf8a5b26162d4a3674846

test:
  secret_key_base: ebacef5525195ec54b66c5ff18e3f5042c63a4659f45cf12dcab8af6aa269416fb125c51098a63902e4e1fd0ad8fa6f7173253f37d958bdc05330f0b8779fc00

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
